apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: hello
  labels:
    app: hello
spec:
  containers:
  - image: nginxdemos/hello:plain-text
    name: hello
    ports:
    - containerPort: 80
      name: web
