apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: nginxdemos/hello:plain-text
          name: hello
          ports:
            - containerPort: 80
              name: web
