apiVersion: v1
kind: Service
metadata:
  name: customer-db
  labels:
    app: customer
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: sql
  selector:
    app: customer
    tier: db
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-db
  labels:
    app: customer
    tier: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer
        tier: db
    spec:
      containers:
        - image: postgres:latest
          name: mysql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: password
            - name: POSTGRES_USER
              value: backend
            - name: POSTGRES_DB
              value: customer            
          ports:
            - containerPort: 5432
              name: sql