apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-backend
  labels:
    app: customer
    tier: backend
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: customer
        tier: backend
    spec:
      containers:
      - image: ??? /customer-backend:latest
        name: lobsters
        env:
        - name: POSTGRES_URL
          value: customer-db:5432/customer
        - name: POSTGRES_USER
          value: backend
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
        ports:
        - containerPort: 8080
          name: web
